###############################################
# Get all users
GET http://localhost:4001/users

###############################################

###############################################
# Create default user
POST http://localhost:4001/users/default

###############################################

###############################################
# Create user
POST http://localhost:4001/users
Content-Type: application/json

{
  "name": "Brad",
  "age": 26
}
###############################################

###############################################
# Get user by name
GET http://localhost:4001/users/Amy
###############################################

###############################################
# Update user by name
PUT http://localhost:4001/users/Amy
Content-Type: application/json

{
  "age": 50
}
###############################################

###############################################
# Delete user by name
DELETE http://localhost:4001/users/Brad
###############################################
